import type { Question } from './types'

// Every question below is adapted from a "Topic Test" or "Case Study" question bank supplied
// in the PDFs, with the correct answer cross-checked against that PDF's own answer key
// (CeMAP 1: the "ANSWERS" section, p.260+; CeMAP 2&3: the answer-key pages at the end of file).
// origin: 'original' marks these as coming directly from supplied material (not freshly
// generated) per your instruction to keep the two clearly separable.
// Option order below matches the source; correctIndex is 0-based into `options`.

export const questions: Question[] = [
  // ================= CeMAP 1, Unit 1, Topic 1 (18 Qs) =================
  q('c1-u1-t1-q1', 'cemap1','unit1','t1','Financial intermediaries can provide maturity transformation because they:',
    ['Offer a wide range of deposit accounts to a wide range of depositors','Aggregate many small deposits from a large number of clients','Provide services to clients from many different geographical locations','Reduce the risk of default or fraud by lending to a wide variety of borrowers'],0,
    'Offering a spread of deposit accounts with different notice/term profiles lets a bank predict withdrawal patterns statistically, which is what allows it to safely fund longer-term lending — this is the mechanism behind maturity transformation.'),
  q('c1-u1-t1-q2','cemap1','unit1','t1','A key difference between a mutual organisation and a proprietary organisation is that a mutual organisation:',
    ['Can issue shares on the stock market','Is owned by members not shareholders','Shares its profits in the form of dividends','Is only allowed to lend to other financial institutions'],1,
    'Mutuals (e.g. many building societies) are owned by their members (savers/borrowers), not by external shareholders.'),
  q('c1-u1-t1-q3','cemap1','unit1','t1','How can a bank involved in wholesale banking raise money quickly to finance its business activities?',
    ['By a further issue of shares','By borrowing from the Bank of England','From the interbank market','By issuing gilts'],2,
    'The interbank market is where banks lend to and borrow from each other wholesale, providing quick access to funds.'),
  q('c1-u1-t1-q4','cemap1','unit1','t1','What is the role of the Bank of England\u2019s Monetary Policy Committee?',
    ['To veto undesirable takeovers','To set capital adequacy levels','To set the Bank of England Base Rate','To set inflation targets'],2,
    'The government sets the inflation target; the MPC\u2019s job is to set the Bank Rate to try to hit that target.'),
  q('c1-u1-t1-q5','cemap1','unit1','t1','To be acceptable as a medium of exchange, money must have all of the following EXCEPT:',
    ['Divisible into small units','Generally acceptable to all parties','Free from the effects of inflation','Sufficient in quantity'],2,
    'Money must be acceptable, divisible and sufficient in quantity — being "free from inflation" is not one of the defining requirements of a medium of exchange.'),
  q('c1-u1-t1-q6','cemap1','unit1','t1','The Bank of England is a central bank because it:',
    ['Deposits money with the International Monetary Fund','Has been approved by the Treasury and lends money direct to other banks','Holds reserves of foreign currency for other banks and institutional investors','Acts as banker to the government, supervises the economy and regulates the supply of money'],3,
    'Being banker to the government, overseeing economic stability and regulating the money supply are the hallmarks of a central bank.'),
  q('c1-u1-t1-q7','cemap1','unit1','t1','Which factor distinguishes building societies from other financial institutions?',
    ['They are mutual institutions owned by their members','They are owned by their shareholders','They only lend for mortgage purposes','They cannot make regulated loans'],0,
    'Mutual ownership by members is the defining feature that separates building societies from proprietary (shareholder-owned) banks.'),
  q('c1-u1-t1-q8','cemap1','unit1','t1','Up to what percentage of their liabilities may building societies raise on the wholesale market?',
    ['50%','25%','100%','40%'],0,
    'Building societies are restricted to raising a maximum of 50% of their funds from wholesale markets, reflecting their mutual, member-funded model.'),
  q('c1-u1-t1-q9','cemap1','unit1','t1','Which of the following is NOT a function of the Bank of England?',
    ['Banker to the UK government','Issuing bank notes','Maintaining economic stability','Providing personal banking facilities'],3,
    'The Bank of England does not provide everyday personal banking services to the public — that is the role of retail banks.'),
  q('c1-u1-t1-q10','cemap1','unit1','t1','Which of the following is NOT one of the properties required for money to be acceptable as a medium of exchange?',
    ['Portability','Divisible into small units','Acceptable to all parties','Limited in quantity'],3,
    'Money needs to be sufficient (not limited) in quantity to function as a medium of exchange.'),
  q('c1-u1-t1-q11','cemap1','unit1','t1','Which of the following is NOT a feature of bonds?',
    ['Coupon','Par value','Redemption date','Variable rates of interest over the term'],3,
    'Bonds pay a fixed coupon for the term — a variable rate of interest is not a feature of a conventional bond.'),
  q('c1-u1-t1-q12','cemap1','unit1','t1','In relation to markets, the \u2018equilibrium price\u2019 usually arises when:',
    ['Supply exceeds demand','Supply and demand are balanced','Demand exceeds supply','Sellers exceed buyers'],1,
    'Equilibrium is, by definition, the point at which supply and demand are equal.'),
  q('c1-u1-t1-q13','cemap1','unit1','t1','From a company perspective, what is the purpose of the equity market?',
    ['Access to borrowing','A facility to buy bonds','Capital raising','Access to investments'],2,
    'Companies issue shares on the equity market primarily to raise capital for the business.'),
  q('c1-u1-t1-q14','cemap1','unit1','t1','The reinsurance market is designed to:',
    ['Enable individuals to arrange insurance','Provide access to specialist insurance policies','Help insurance companies to manage risk','Help existing insurance policy holders to switch policies'],2,
    'Reinsurance lets insurers pass on (share) some of their own risk to other insurers, helping manage large or concentrated exposures.'),
  q('c1-u1-t1-q15','cemap1','unit1','t1','The main legislation covering money laundering is the:',
    ['Fraud Act 2006','Theft Act 1968','Proceeds of Crime Act 2002','Bribery Act 2010'],2,
    'The Proceeds of Crime Act 2002 is the principal UK anti-money laundering statute.'),
  q('c1-u1-t1-q16','cemap1','unit1','t1','A bank uses deposits from a number of savers to provide a loan to a borrower. This is an example of:',
    ['Aggregation','Maturity transformation','Risk transformation','Disintermediation'],0,
    'Simply pooling many small deposits into one larger loan (with no mention of a term/maturity mismatch) describes aggregation.'),
  q('c1-u1-t1-q17','cemap1','unit1','t1','Who, or what, owns a building society?',
    ['Its shareholders','Its savers and borrowers','A parent company','All its customers'],1,
    'As a mutual, a building society is owned by its members — its savers and borrowers.'),
  q('c1-u1-t1-q18','cemap1','unit1','t1','Which of these stock markets is based in France?',
    ['Nikkei','Dow Jones','Dax','CAC'],3,
    'The CAC 40 is France\u2019s main stock market index (the Nikkei is Japanese, the Dow Jones is American, and the Dax is German).'),

  // ================= CeMAP 1, Unit 1, Topic 2 Part 1 (12 Qs) =================
  q('c1-u1-t2a-q1','cemap1','unit1','t2a','The key macroeconomic objective of most governments does NOT include:',
    ['Balance of payments equilibrium','100% employment','Price stability','Satisfactory economic growth'],1,
    '"Full employment" is generally understood as a small residual level of unemployment, not literally 100% employment — a genuine objective would never target 100%.'),
  q('c1-u1-t2a-q2','cemap1','unit1','t2a','What is the target rate of inflation, as measured by the Consumer Price Index, that the government hopes to achieve?',
    ['3%','5%','2%','1%'],2,
    'The UK inflation target set for the Bank of England\u2019s MPC is 2%, measured by CPI.'),
  q('c1-u1-t2a-q3','cemap1','unit1','t2a','The European Union issues a new Directive. This means each member state:',
    ['Must implement the Directive in its entirety within the specified timescale','Can choose whether or not to adopt the Directive','Has the choice of how to meet the Directive\u2019s objectives','Must implement the Directive, provided the state is part of the Eurozone'],2,
    'Directives are binding as to the outcome/objective but leave the method of achieving it to each state — unlike Regulations, which bind in their entirety.'),
  q('c1-u1-t2a-q4','cemap1','unit1','t2a','The UK financial services regulatory framework is a four-tier process. Which body has taken over activities in the second tier?',
    ['The Financial Ombudsman Service','The FSA','The PRA and FCA','The Lenders Code'],2,
    'The second tier is the UK regulatory bodies — now the PRA and FCA, having replaced the former FSA.'),
  q('c1-u1-t2a-q5','cemap1','unit1','t2a','Which index does the government use to assess the inflation rate for targeting purposes?',
    ['Retail Prices Index','Consumer Prices Index','Construction and Building Prices Index','FTSE 100 Index'],1,
    'The Consumer Prices Index (CPI) is the official measure used for the 2% inflation target.'),
  q('c1-u1-t2a-q6','cemap1','unit1','t2a','Under what circumstances can a nation state opt out of a regulation laid down by the European Council and Council of Ministers?',
    ['None','Only if specific dispensation has been granted','Only if an alternative approach has been agreed','Only if the member joined within the previous three years'],1,
    'EU Regulations are directly applicable to all member states unless a specific dispensation has been granted.'),
  q('c1-u1-t2a-q7','cemap1','unit1','t2a','Which type(s) of policy are used by governments to achieve their long-term economic objectives?',
    ['Fiscal only','Monetary only','Monetary and fiscal','Neither monetary nor fiscal'],2,
    'Governments typically use a combination of both fiscal (tax/spend) and monetary (interest rate) policy.'),
  q('c1-u1-t2a-q8','cemap1','unit1','t2a','In what phase of the economic cycle might the Bank of England raise interest rates to control consumer spending and dampen inflation?',
    ['Recovery','Boom','Contraction','Recession'],1,
    'During a boom, inflationary pressure is high, so the Bank is more likely to raise rates to cool spending.'),
  q('c1-u1-t2a-q9','cemap1','unit1','t2a','Which of the following is NOT a main component of a government\u2019s fiscal policy?',
    ['Spending','Taxation','Borrowing','Interest rates'],3,
    'Interest rates are a monetary policy tool (set by the Bank of England), not a component of fiscal policy.'),
  q('c1-u1-t2a-q10','cemap1','unit1','t2a','What action is a government most likely to take first when there is a deficit in its current account?',
    ['Reduce interest rates','Cancel tariffs and import quotas','Use its foreign currency reserves','Impose exchange controls'],2,
    'A government typically draws on its foreign currency reserves first to cover a current account deficit before resorting to more drastic measures.'),
  q('c1-u1-t2a-q11','cemap1','unit1','t2a','Prices rose 3% this month, compared to a 4% increase last month. This represents:',
    ['Reflation','Deflation','Disinflation','Stagflation'],2,
    'Prices are still rising, just at a slower rate than before — that is disinflation, not deflation (which requires falling prices).'),
  q('c1-u1-t2a-q12','cemap1','unit1','t2a','Which combination of figures would result in the highest approximate real interest rate?',
    ['Nominal interest 4%, inflation 2.5%','Nominal interest 3%, inflation 2%','Nominal interest 5%, inflation 7%','Nominal interest 7%, inflation 6%'],0,
    'Real rate ≈ nominal − inflation: 4−2.5=1.5% is the highest of the four options (compared with 1%, −2% and 1%).', true),

  // ================= CeMAP 1, Unit 1, Topic 2 Part 2 — Taxation (16 Qs) =================
  q('c1-u1-t2b-q1','cemap1','unit1','t2b','The profits of a sole trader are subject to which class of National Insurance contributions?',
    ['Class 4','Class 3','Class 2','Class 1'],0,
    'Self-employed profits attract Class 4 NICs, paid via self-assessment alongside income tax.'),
  q('c1-u1-t2b-q2','cemap1','unit1','t2b','What is the minimum number of days William must have been in the UK in the tax year to be deemed UK tax resident?',
    ['1 day','183 days','90 days','365 days'],1,
    '183 days or more in a tax year automatically establishes UK tax residence.'),
  q('c1-u1-t2b-q3','cemap1','unit1','t2b','Which of the following is normally exempt from capital gains tax on disposal where a gain has been made?',
    ['A holiday home','Shares in UK companies','Currency speculation','Ordinary private cars'],3,
    'Cars kept for normal use are exempt from CGT; the other options are all potentially chargeable gains.'),
  q('c1-u1-t2b-q4','cemap1','unit1','t2b','Suzy sold an antique vase at a profit. Which of the following can she NOT offset against her CGT liability?',
    ['The original cost of the vase','The cost of repairing a hairline crack','Advertising costs','The auctioneer\u2019s commission for the sale'],1,
    'Repair/maintenance costs are not an allowable CGT deduction — only acquisition, enhancement and disposal costs qualify.'),
  q('c1-u1-t2b-q5','cemap1','unit1','t2b','Which of the following transactions would be subject to capital gains tax?',
    ['Shares in a FTSE 100 company bought for £20,000 and sold for £100,000','A painting valued at £5,000 but sold for a profit','A life insurance policy surrendered by the original investor at a profit','Government stocks bought for £20,000 and sold at a profit'],0,
    'Shares are a standard chargeable asset for CGT; gilts, and life policy gains for the original owner, are both exempt (and the painting example here falls under the chattels exemption threshold).'),
  q('c1-u1-t2b-q6','cemap1','unit1','t2b','Which disposal may incur a liability to CGT at the time of disposal?',
    ['A UK resident selling their holiday home in Spain for a profit','Transfers between spouses who are living together','Disposals to recognised charities','The deemed disposal of assets on an individual\u2019s death'],0,
    'A holiday home abroad is not a main residence, so a UK resident\u2019s gain on it is chargeable; the other three are all specifically exempt/excluded from an immediate CGT charge.'),
  q('c1-u1-t2b-q7','cemap1','unit1','t2b','What exactly are \u2018allowable deductions\u2019 in calculating a CGT liability?',
    ['Government fixed allowances against CGT liability','The annual exemption limit only','Costs incurred in acquiring, enhancing and disposing of an asset','The annual exemption limit and the indexation allowance'],2,
    'Allowable deductions are the actual costs of acquiring, improving and disposing of the asset — not a fixed allowance.'),
  q('c1-u1-t2b-q8','cemap1','unit1','t2b','What is the position when a capital loss is made on disposal of an asset?',
    ['It is not relevant to CGT calculations','It must be carried forward to the next tax year to offset future gains','It can be offset initially against gains made in the year the loss occurred','It should be carried back to the previous year'],2,
    'A loss is set first against gains in the same tax year; only any unused balance carries forward.'),
  q('c1-u1-t2b-q9','cemap1','unit1','t2b','Which of the following assets would be exempt from capital gains tax?',
    ['A vintage motor car sold for a profit','A Spanish property used for holiday visits','Euros held for use on foreign holidays','Shares purchased on the UK stock market'],2,
    'Foreign currency held for personal/holiday use is exempt from CGT; the other options are all potentially chargeable.'),
  q('c1-u1-t2b-q10','cemap1','unit1','t2b','In May 2022, Peter gifted £500,000 to his son Paul. Peter died in June 2025 leaving an estate of £750,000. Which IHT rate applies to at least part of the £500,000 gift?',
    ['0%','24%','32%','40%'],2,
    'Peter survived roughly 3 years after the gift, so taper relief reduces the rate charged on the part of the gift above the nil rate band to 32% (80% of the full 40% rate).', undefined, true),
  q('c1-u1-t2b-q11','cemap1','unit1','t2b','Julian died leaving an estate of £350,000, having made no previous gifts, split equally between his son and his wife. What IHT was due, based on a nil rate band of £325,000?',
    ['Nil','£43,200','£30,000','£140,000'],0,
    'The half passing to his wife is spouse-exempt; the £175,000 passing to his son is comfortably within the £325,000 nil rate band, so no IHT is due.', undefined, true),
  q('c1-u1-t2b-q12','cemap1','unit1','t2b','Fiona sold an investment property, realising a £120,000 gain. Which of the following can she NOT deduct from the gain?',
    ['The original cost of the property','The cost of an extension to the property','The legal costs of selling the property','The cost of replacing broken windows'],3,
    'Replacing broken windows is a repair, not an improvement — repair costs are not an allowable CGT deduction.'),
  q('c1-u1-t2b-q13','cemap1','unit1','t2b','When is tax due to be paid following a \u2018chargeable lifetime transfer\u2019?',
    ['Immediately','After 6 years','After 7 years','Following the death of the donor'],0,
    'A chargeable lifetime transfer (e.g. into most trusts) can trigger an immediate lifetime IHT charge if it exceeds the available nil rate band.'),
  q('c1-u1-t2b-q14','cemap1','unit1','t2b','In the event of a transfer on death, where does the liability for IHT payment fall?',
    ['On the donor','On the deceased\u2019s spouse or next of kin','On the deceased\u2019s estate','On the deceased\u2019s life assurance company'],2,
    'IHT is charged against the deceased\u2019s estate, administered by the personal representatives.'),
  q('c1-u1-t2b-q15','cemap1','unit1','t2b','Assuming the annual gift allowance for IHT remains £3,000, what exemption is available in year four if it was NOT used in the preceding three years?',
    ['None','£3,000','£6,000','£12,000'],2,
    'The annual exemption can only be carried forward one year if unused — it does not accumulate over multiple years, so the maximum available is £6,000 (current year + one carried-forward year).', undefined, true),
  q('c1-u1-t2b-q16','cemap1','unit1','t2b','Where shares are purchased using an electronic trading system, which is true?',
    ['The buyer pays VAT','The shares transfer can be registered before the documents are stamped','The transaction will not be subject to stamp duty reserve tax','Stamp duty reserve tax will be deducted automatically and passed to HMRC'],3,
    'Electronic (CREST) share transactions have SDRT deducted automatically and passed to HMRC.'),

  // ================= CeMAP 2, Unit 2, Topic 1 — Mortgage Repayment Methods (12 Qs) =================
  q('c2-u2-t1-q1','cemap2','unit2','t1','Which statement regarding interest payments on a repayment mortgage is TRUE?',
    ['The first year\u2019s payments are mainly interest, progressively becoming a greater proportion of capital','The first year\u2019s payments are mainly capital, progressively becoming a greater proportion of interest','The capital and interest elements remain constant throughout the term','All of the payment is interest on a repayment mortgage'],0,
    'Early payments are mostly interest; the balance shifts towards capital as the outstanding debt reduces.'),
  q('c2-u2-t1-q2','cemap2','unit2','t1','A possible drawback of a capital and interest mortgage is that it:',
    ['Cannot be topped up','Is always more expensive than other methods','May not fully repay the loan','Requires additional life assurance'],3,
    'Unlike an endowment mortgage, a repayment mortgage has no built-in life cover — the borrower must arrange separate (usually decreasing term) assurance.'),
  q('c2-u2-t1-q3','cemap2','unit2','t1','Some borrowers like to feel the amount they owe is reducing with every payment. They should choose a:',
    ['Fixed rate mortgage','Endowment mortgage','Repayment mortgage','ISA mortgage'],2,
    'A repayment (capital and interest) mortgage guarantees the outstanding balance falls with every payment made.'),
  q('c2-u2-t1-q4','cemap2','unit2','t1','Which interest accounting method fails to penalise late payers of their monthly payments?',
    ['Annual review system','Annual rest system','Daily interest','Fixed payments'],1,
    'Under annual rest, the year\u2019s interest is calculated and debited up front, so a late payment part-way through the year has no immediate effect on interest charged.'),
  q('c2-u2-t1-q5','cemap2','unit2','t1','Alison wants an interest payment method that benefits her if she makes some payments early. She should choose:',
    ['Fixed payments','Annual rest','Daily interest','Annual review'],2,
    'Daily rest recalculates interest every day, so an early/extra payment reduces the balance — and interest charged — immediately.'),
  q('c2-u2-t1-q6','cemap2','unit2','t1','John has a 20-year repayment mortgage of £75,000 on an annual rest basis at a fixed 6% for year one, with repayments of £7.30 per £1,000 borrowed. How much capital does he repay in the first year?',
    ['£1,090','£1,640','£1,900','£2,070'],3,
    'Monthly payment = £7.30 × 75 = £547.50, so annual payment = £6,570. Annual interest = £75,000 × 6% = £4,500. Capital repaid = £6,570 − £4,500 = £2,070.', undefined, undefined, true),
  q('c2-u2-t1-q7','cemap2','unit2','t1','Which of the following is EXCLUDED by a lender when calculating the APRC?',
    ['Building insurance','Mortgage valuation fees','Arrangement fees','Associated life assurance premiums'],3,
    'Life assurance premiums are specifically excluded from the APRC calculation, along with early repayment charges and default charges.'),
  q('c2-u2-t1-q8','cemap2','unit2','t1','With a 25-year repayment mortgage where payments are made on time, which statement about the monthly payment is true?',
    ['More capital is repaid each month if interest rates rise','Payments in the early years are more capital than interest','Payments in the final years are more capital than interest','Payments are evenly balanced between capital and interest throughout'],2,
    'As the outstanding balance falls, the interest portion shrinks and the capital portion grows — so later payments are mostly capital.'),
  q('c2-u2-t1-q9','cemap2','unit2','t1','Which statement is true in relation to interest-only mortgages?',
    ['All customers are subject to the same rules on interest-only mortgages','Lenders must review the repayment vehicle during the last 5 years of the term','Relying on house price inflation is not an acceptable repayment strategy','The lender must provide advice on a credible repayment vehicle'],2,
    'Speculative strategies such as relying on house price inflation are not accepted as a credible interest-only repayment strategy.'),
  q('c2-u2-t1-q10','cemap2','unit2','t1','Which is a feature of a repayment mortgage?',
    ['Repayments are fixed throughout the term','The capital and interest payment proportions change over the term','The capital balance does not reduce over the term','The borrower must take out an investment policy to cover a shortfall'],1,
    'The capital/interest split shifts progressively over the term as the outstanding balance reduces.'),
  q('c2-u2-t1-q11','cemap2','unit2','t1','If Kim and Chris opt for a repayment mortgage, the most suitable way to ensure the loan is repaid if one of them dies is:',
    ['Contributions to a critical illness policy','Joint life decreasing-term assurance','Investing in an endowment assurance','Contributing to a permanent health insurance policy'],1,
    'Decreasing term assurance mirrors the falling balance of a repayment mortgage and is the standard low-cost cover for this need.'),
  q('c2-u2-t1-q12','cemap2','unit2','t1','Which is true of capital repayments on a repayment mortgage?',
    ['It reduces by an even amount each year','Most capital is repaid towards the beginning of the term','Most capital is repaid towards the end of the term','It remains the same'],2,
    'The capital repayment element accelerates over the term, so most of the capital is repaid in the later years.'),

  // ================= CeMAP 3, Case Study 1 — Luke and Jessica (10 Qs) =================
  q('c3-u1-t1-q1','cemap3','unit1','t1','Assuming the maximum £96,000 loan is taken, what procuration fee (0.35% of advance, minimum £250) must the broker declare?',
    ['Up to £250','£250','£329','£336'],3,
    '£96,000 × 0.35% = £336, which exceeds the £250 minimum, so £336 is the fee that must be declared.', undefined, undefined, true),
  q('c3-u1-t1-q2','cemap3','unit1','t1','When deciding the rate to use for an affordability stress test, the lender must consider:',
    ['Market expectations and the latest Financial Policy Committee recommendation','Its own expectations and the latest Bank of England recommendation','Market expectations and the latest FCA recommendation','Market expectations with a maximum interest rate of 1%'],0,
    'Lenders must factor in market expectations for future rate rises together with the Financial Policy Committee\u2019s recommendation when setting the stress test rate.'),
  q('c3-u1-t1-q3','cemap3','unit1','t1','If Luke and Jessica use all of Luke\u2019s £46,000 savings as a deposit on the £140,000 purchase, ignoring other costs, their initial monthly payment (at £4.58 per £1,000 borrowed) will be:',
    ['£210.72','£215.20','£430.52','£439.68'],2,
    'Loan = £140,000 − £46,000 = £94,000. £94 × £4.58 = £430.52 per month.', undefined, undefined, true),
  q('c3-u1-t1-q4','cemap3','unit1','t1','The valuation on Luke and Jessica\u2019s new property required an "undertaking". This indicates that:',
    ['A specialist report will be required','The full advance will be retained until work is completed','The lender may require a second inspection, although this is not always the case','The loan will be made in two stages, with the second payment after completion'],2,
    'An undertaking typically requires confirmation that identified work will be completed, and the lender may (but won\u2019t always) want to re-inspect to confirm this.'),
  q('c3-u1-t1-q5','cemap3','unit1','t1','Luke\u2019s idea of using his personal pension plan to repay the mortgage (as his brother did) is unsuitable mainly because of his:',
    ['Age','Employment status','Protection needs','Tax status'],0,
    'At 23, Luke is far too young to be able to access his pension to repay a mortgage in any realistic timeframe, making a pension-based repayment strategy unsuitable.'),
  q('c3-u1-t1-q6','cemap3','unit1','t1','In connection with the recommended base rate tracker mortgage, Luke and Jessica should be aware that the interest rate may change:',
    ['Daily','Monthly','Quarterly','Annually'],1,
    'A base rate tracker moves in line with the Bank of England Base Rate, which the MPC reviews and can change at its (broadly monthly) meetings.'),
  q('c3-u1-t1-q7','cemap3','unit1','t1','In connection with the repayment method chosen by Luke\u2019s brother (a personal pension), which is correct?',
    ['He could take more than 25% of the fund as a lump sum, but the excess over 25% would be taxable','Luke could receive tax relief on up to £40,000 in this tax year assuming his income stays the same','He would have to take an income at the same time as taking any lump sum','The fund would be subject to inheritance tax on Luke\u2019s death prior to retirement'],0,
    'Pension savings allow up to 25% to be taken tax-free; any amount taken above that is subject to income tax.'),
  q('c3-u1-t1-q8','cemap3','unit1','t1','Bearing in mind Luke\u2019s need for low-cost, short-term protection against being unable to work, which product is most suitable?',
    ['Critical illness cover','Mortgage payment protection insurance','Permanent health insurance','Private medical insurance'],1,
    'Mortgage payment protection insurance (MPPI) is a lower-cost, short-term option well suited to covering mortgage payments while a self-employed income is still building.'),
  q('c3-u1-t1-q9','cemap3','unit1','t1','Which is true regarding the most appropriate form of life cover for Luke and Jessica?',
    ['A separate policy for each of them is necessary','The sum assured will stay level throughout the policy','Premiums will remain level throughout the term','Tax relief on the premiums is available'],2,
    'A joint life decreasing term policy suited to their repayment mortgage would have level (fixed) premiums, even though the sum assured itself decreases over the term.'),
  q('c3-u1-t1-q10','cemap3','unit1','t1','If Luke and Jessica proceed with a repayment mortgage, what advantage does this have over the interest-only-with-pension method used by Luke\u2019s brother?',
    ['Guaranteed portability of product terms','Gradually increasing equity','Integrated life cover','Lower legal fees'],1,
    'A repayment mortgage steadily builds the borrower\u2019s equity in the property, unlike an interest-only loan where the balance stays the same until the repayment vehicle pays out.'),

  // ================= CeMAP 1, Unit 1, Topic 3 — State Benefits (16 Qs) =================
  q('c1-u1-t3-q1','cemap1','unit1','t3','New style Jobseeker\u2019s Allowance depends on having paid which class(es) of National Insurance contributions?',
    ['Class 1 or Class 4', 'Class 1 or Class 3', 'Class 1 only', 'Class 4 only'],2,
    'New style JSA is based specifically on Class 1 (employee) National Insurance contributions.'),
  q('c1-u1-t3-q2','cemap1','unit1','t3','What is the maximum period for which Statutory Maternity Pay (SMP) can be claimed?',
    ['11 weeks', '15 weeks', '18 weeks', '39 weeks'],3,
    'SMP is payable for a maximum of 39 weeks.'),
  q('c1-u1-t3-q3','cemap1','unit1','t3','Mandy is pregnant with her first baby and has been a full-time self-employed graphic designer for two years. What benefit may she claim before the baby is born?',
    ['Statutory Maternity Pay', 'Maternity Allowance', 'Child Benefit', 'Income Support'],1,
    'As a self-employed person, Mandy cannot claim SMP (which requires an employer) and would instead claim Maternity Allowance.'),
  q('c1-u1-t3-q4','cemap1','unit1','t3','To which state benefit would a self-employed person be entitled?',
    ['Statutory Sick Pay', 'Statutory Maternity Pay', 'State Second Pension', 'Basic State Pension'],3,
    'Statutory Sick Pay and Statutory Maternity Pay both require an employer; the self-employed can still qualify for the (basic/new) State Pension through their own NICs.'),
  q('c1-u1-t3-q5','cemap1','unit1','t3','Mrs Turner is a single parent with a 10-year-old child. How is the Child Benefit she receives treated?',
    ['Tax free', 'Taxable at the lower rate', 'Taxable at the basic rate', 'Taxable at her marginal rate'],0,
    'Child Benefit itself is tax-free; a separate tax charge only applies where a partner\u2019s income exceeds the relevant threshold.'),
  q('c1-u1-t3-q6','cemap1','unit1','t3','Which tax-free weekly benefit is for people disabled at or after state pension age who need a lot of looking after?',
    ['Invalidity benefit', 'Severe disablement allowance', 'Attendance Allowance', 'Disability Living Allowance'],2,
    'Attendance Allowance is specifically for those who have reached state pension age and need help with personal care.'),
  q('c1-u1-t3-q7','cemap1','unit1','t3','New style Jobseeker\u2019s Allowance is payable for a MAXIMUM of:',
    ['3 months', '6 months', '1 year', '2 years'],1,
    'New style JSA is capped at a maximum of 6 months regardless of income or savings.'),
  q('c1-u1-t3-q8','cemap1','unit1','t3','Which benefit has NOT been replaced by Universal Credit?',
    ['Income Support', 'Income-based Jobseeker\u2019s Allowance', 'Income-related Employment and Support Allowance', 'Attendance Allowance'],3,
    'Attendance Allowance sits entirely outside Universal Credit and was never one of the six legacy benefits it replaced.'),
  q('c1-u1-t3-q9','cemap1','unit1','t3','Which is NOT a feature of new style Jobseeker\u2019s Allowance?',
    ['Only available to claimants who have made NICs', 'Only available to claimants with savings below £6,000', 'Benefits are taxable', 'Claimants are credited with NICs'],1,
    'New style JSA is not means-tested, so there is no savings-based restriction on eligibility — that description does not apply to it.'),
  q('c1-u1-t3-q10','cemap1','unit1','t3','James has worked in IT for 12 years and his fixed-term contract is ending. Having made NICs throughout, what benefit is he likely able to claim while unemployed?',
    ['Working Tax Credit', 'Income Support', 'New style Jobseeker\u2019s Allowance', 'New style Employment and Support Allowance'],2,
    'Having built up a qualifying NIC record and simply being unemployed (not unable to work through illness), new style JSA is the appropriate benefit.'),
  q('c1-u1-t3-q11','cemap1','unit1','t3','Aliyah has worked for her employer for 16 weeks and is 24 weeks pregnant. Which benefit may she be entitled to?',
    ['Statutory Maternity Pay', 'Income Support', 'Child Tax Credit', 'Maternity Allowance'],3,
    'SMP requires 26 weeks\u2019 continuous employment including the qualifying week — Aliyah doesn\u2019t meet this, so Maternity Allowance is the relevant option.'),
  q('c1-u1-t3-q12','cemap1','unit1','t3','When is the earliest that Maternity Allowance can be claimed?',
    ['When the baby is born', '4 weeks before the baby is due', '11 weeks before the baby is due', '16 weeks before the baby is due'],2,
    'Maternity Allowance can begin as early as 11 weeks before the baby is due, matching the earliest SMP start date.'),
  q('c1-u1-t3-q13','cemap1','unit1','t3','Malcolm, 42 and self-employed, has fallen ill and cannot work. Which benefit might he be entitled to?',
    ['Personal Independence Payment', 'Statutory Sick Pay', 'New style Employment and Support Allowance', 'Attendance Allowance'],2,
    'New style ESA is available to the self-employed and unemployed who cannot work due to illness or disability, based on their NIC record.'),
  q('c1-u1-t3-q14','cemap1','unit1','t3','Lucy earns £62,000 and her partner Howard earns £29,000. They have three children, one of whom is 18 and studying A-levels. Assuming a £60,000 Child Benefit threshold, for how many children can they claim?',
    ['Two — the eldest is excluded for being over 16', 'All three, as all three are in full-time education', 'None, because Lucy earns over £60,000', 'None, because their combined income exceeds £60,000'],1,
    'Child Benefit eligibility isn\u2019t based on the number of children being restricted by income — all three remain eligible (the 18-year-old still counts while in full-time non-advanced education); the high-income tax charge is a separate matter from eligibility itself.'),
  q('c1-u1-t3-q15','cemap1','unit1','t3','Ian retired at 66 having paid NICs for 33 years, including a 3-year career break caring for his sick partner. Is he eligible for a full new state pension?',
    ['No, because he wasn\u2019t continuously employed throughout his working life', 'No, because he retired too early to claim the new state pension', 'Yes, because he paid NICs for more than 30 years', 'Yes, because he would have been credited with NICs while a carer'],3,
    'Carers are credited with NICs for time spent caring, which — combined with his 33 years of actual contributions — is likely to give Ian the 35 qualifying years needed for a full pension.'),
  q('c1-u1-t3-q16','cemap1','unit1','t3','Lydia is 20 and has just begun a permanent full-time job. Which of the following is true?',
    ['She will need 30 years of NICs for the full state pension', 'She will need 35 years of NICs for the full state pension', 'She will qualify for some state pension after one year of contributions', 'She will qualify for some state pension after five years of contributions'],1,
    'The new state pension requires 35 qualifying years of NICs for the maximum amount.'),

  // ================= CeMAP 1, Unit 1, Topic 4 Part 1 — Protection (16 Qs) =================
  q('c1-u1-t4a-q1','cemap1','unit1','t4a','With reference to the hierarchy of financial needs, which need would usually be addressed after all other needs have been met?',
    ['Retirement', 'Income protection', 'Investment', 'Living today'],2,
    'Investment for the future sits at the top of the hierarchy — addressed only once living costs, protection, income protection, pension and savings needs are covered.'),
  q('c1-u1-t4a-q2','cemap1','unit1','t4a','Which life assurance arrangement does NOT represent an insurable interest?',
    ['A £50,000 policy on the life of someone who owes the policyholder £50,000', 'A £50,000 policy on a parent\u2019s life', 'A £50,000 policy on a spouse\u2019s life', 'A £50,000 policy on a business partner\u2019s life'],1,
    'There is no automatic insurable interest between parents and children — the other three all involve a recognised financial interest.'),
  q('c1-u1-t4a-q3','cemap1','unit1','t4a','Malika wants financial security for her children if she dies before they are adults, but is concerned about cost. What type of policy is most cost-effective?',
    ['Critical illness', 'Whole of life', 'Level term', 'Income Protection'],2,
    'Level term assurance provides a fixed sum on death within the term at a much lower cost than whole-of-life cover.'),
  q('c1-u1-t4a-q4','cemap1','unit1','t4a','Critical illness policies:',
    ['Pay the sum assured on diagnosis of any serious illness', 'Pay the benefit as a taxable lump sum', 'Are available only as term or whole-of-life policies', 'May feature a survival period before benefits are paid'],3,
    'Standalone critical illness policies typically require the policyholder to survive a defined period after diagnosis before a claim is paid.'),
  q('c1-u1-t4a-q5','cemap1','unit1','t4a','What is the main difference between ASU policies and income protection insurance?',
    ['ASU provides short-term cover only', 'ASU does not have a deferred payment period', 'ASU provides for other employment scenarios, not just redundancy', 'ASU provides total protection for all income'],0,
    'ASU policies are annually renewable and typically pay benefits for only 1-2 years, making them shorter-term cover than income protection insurance.'),
  q('c1-u1-t4a-q6','cemap1','unit1','t4a','Julian wants to cover his essential outgoings if unable to work due to medium or long-term illness. Which product is most suitable?',
    ['Accident and sickness', 'Critical Illness', 'Income Protection', 'Private Medical'],2,
    'Income protection insurance is specifically designed for ongoing replacement income during medium/long-term incapacity.'),
  q('c1-u1-t4a-q7','cemap1','unit1','t4a','What is usually the MAXIMUM benefit payment period for ASU policies?',
    ['1 year', '2 years', '5 years', '7 years'],1,
    'ASU policies typically cease paying benefits after 1-2 years, unlike income protection which can run to retirement.'),
  q('c1-u1-t4a-q8','cemap1','unit1','t4a','Which is normally covered as standard in the majority of buildings insurance policies?',
    ['Accidental damage', 'Third party liability', 'Riot or civil commotion', 'Civil war or insurrection'],2,
    'Riot, strike or civil disturbance damage is a standard risk covered by most buildings policies; accidental damage is usually an optional extra.'),
  q('c1-u1-t4a-q9','cemap1','unit1','t4a','Which statement is true regarding income protection or critical illness cover?',
    ['There is no limit to the benefit level on an income protection plan', 'CIC premiums qualify for tax relief for retired policyholders', 'CIC provides a taxable lump sum on diagnosis', 'There is no limit to the number of claims on an IPI policy'],3,
    'Provided premiums are kept up to date, an income protection policy can be claimed against repeatedly for qualifying periods of incapacity over its term.'),
  q('c1-u1-t4a-q10','cemap1','unit1','t4a','Which is correct regarding critical illness insurance?',
    ['The monthly benefit from a CIC policy is taxed as income', 'The lump sum benefit under CIC is free from all UK taxes', 'CIC premiums attract tax relief at the policyholder\u2019s marginal rate', 'Monthly CIC benefit is limited to 60% of pre-disability income'],1,
    'The critical illness lump sum is paid entirely tax-free to the policyholder.'),
  q('c1-u1-t4a-q11','cemap1','unit1','t4a','What type of assurance is a family income benefit plan?',
    ['Level term', 'Decreasing term', 'Whole-of-life', 'Endowment'],1,
    'Family income benefit is a form of decreasing term assurance, since the total potential future payments reduce the longer the insured survives.'),
  q('c1-u1-t4a-q12','cemap1','unit1','t4a','Which should be a priority consideration when assessing the needs of retired couples?',
    ['Pensions planning', 'Protection advice', 'Inheritance Tax planning', 'Mortgage advice'],2,
    'For retired couples, protection needs are usually largely met already, making IHT and estate planning a higher priority.'),
  q('c1-u1-t4a-q13','cemap1','unit1','t4a','Which financial planning need is usually the recommended priority for young families?',
    ['Investment', 'Savings', 'Protection', 'Pension planning'],2,
    'Protecting the income of the main breadwinner is the priority need identified for young families in the hierarchy of needs.'),
  q('c1-u1-t4a-q14','cemap1','unit1','t4a','Typical financial needs can be identified based on a person\u2019s:',
    ['Academic background', 'Financial liabilities', 'Life stage', 'Income'],2,
    'The financial life cycle framework groups typical needs by life stage (young adult, young family, established family, mature household, retirement).'),
  q('c1-u1-t4a-q15','cemap1','unit1','t4a','Which is NOT a cross-cutting obligation under the Consumer Duty rules?',
    ['Act in good faith', 'Promote competition', 'Avoid foreseeable harm to customers', 'Enable and support customers to pursue their financial objectives'],1,
    'Promoting competition is not one of the Consumer Duty\u2019s three cross-cutting obligations — those are acting in good faith, avoiding foreseeable harm, and supporting customers\u2019 objectives.'),
  q('c1-u1-t4a-q16','cemap1','unit1','t4a','Which group of the UK population is most likely to be \u2018asset rich, income poor\u2019?',
    ['Young professionals', 'Established families', 'Mature households', 'Retirees'],3,
    'Retirees often hold significant assets (e.g. property) but have limited ongoing income, the classic "asset rich, income poor" position.'),

  // ================= CeMAP 1, Unit 1, Topic 4 Part 2 — Savings & Investments (17 Qs) =================
  q('c1-u1-t4b-q1','cemap1','unit1','t4b','The maximum term of newly issued gilts is usually up to:',
    ['5 years', '10 years', '25 years', '30 years'],3,
    'Gilts are typically issued with terms of up to around 30 years.'),
  q('c1-u1-t4b-q2','cemap1','unit1','t4b','Which of the following is true?',
    ['Dividends are taxed at standard income tax rates', 'Shares have a guaranteed redemption value after a set period', 'A share\u2019s market value will reflect the company\u2019s true value', 'Companies are not obliged to pay dividends'],3,
    'Dividend payments are always at the company\u2019s discretion — there is no obligation to pay them.'),
  q('c1-u1-t4b-q3','cemap1','unit1','t4b','Someone investing in unit trusts would buy units at the:',
    ['Bid price', 'Dilution levy price', 'Offer price', 'Cancellation price'],2,
    'Investors buy unit trust units at the (higher) offer price; the manager buys them back at the (lower) bid price.'),
  q('c1-u1-t4b-q4','cemap1','unit1','t4b','Which is true regarding investment trusts?',
    ['The number of shares is fixed and cannot be increased', 'Shares are subject to an initial charge of 1-3%', 'The fund manager is liable to CGT on gains within the fund', 'The manager must buy back shares from investors on request'],0,
    'Investment trusts are close-ended companies with a fixed share count, unlike open-ended unit trusts/OEICs.'),
  q('c1-u1-t4b-q5','cemap1','unit1','t4b','Jane bought a corporate bond at launch for £100 at a 3% rate. The market now demands a 5% yield on similar bonds. What is the likely effect on the bond\u2019s price today?',
    ['The price will remain the same as when issued', 'The price will be the same as when Jane bought it', 'The bond\u2019s interest rate will rise to match the market', 'The bond\u2019s market price will be lower than when it was issued'],3,
    'Since new buyers can get 5% elsewhere, Jane\u2019s 3%-coupon bond will only sell at a discount to its original price.'),
  q('c1-u1-t4b-q6','cemap1','unit1','t4b','Viraj is a first-time investor with a lump sum, wanting share-like growth potential but nervous about risk. What is most suitable?',
    ['Unit trust', 'A venture capital trust', 'Enterprise Investment Scheme', 'Corporate bond fund'],0,
    'A unit trust offers diversified equity exposure with professional management, moderating single-company risk compared with VCTs or EIS.'),
  q('c1-u1-t4b-q7','cemap1','unit1','t4b','An investment trust must pay out what minimum percentage of income received as dividends?',
    ['50%', '75%', '85%', '100%'],2,
    'Investment trusts must distribute at least 85% of the income they generate to shareholders as dividends.'),
  q('c1-u1-t4b-q8','cemap1','unit1','t4b','The principal difference between corporate bonds and gilts is that corporate bonds:',
    ['Usually pay variable rate interest', 'Are available for larger amounts', 'Normally have no specified redemption date', 'Are considered higher risk investments'],3,
    'Corporate bonds carry greater default risk than gilts (backed by the UK government), so they are considered higher risk and typically pay more.'),
  q('c1-u1-t4b-q9','cemap1','unit1','t4b','The risk of investment fluctuations can be reduced through which feature of the investment process?',
    ['Clustering', 'Dynamisation', 'Diversification', 'Gearing'],2,
    'Diversification — spreading investment across companies, sectors and countries — reduces (though doesn\u2019t eliminate) risk.'),
  q('c1-u1-t4b-q10','cemap1','unit1','t4b','Which is NOT true regarding ownership of shares?',
    ['There is no automatic right to receive dividends', 'Dividends are paid gross but subject to income tax', 'The shareholder is liable for the debts of the company', 'Shares are not as liquid as cash'],2,
    'Shareholders have no liability for company debts beyond the value of their shareholding — limited liability is a core feature of share ownership.'),
  q('c1-u1-t4b-q11','cemap1','unit1','t4b','When managing unit trusts, what does the term \u2018open-ended\u2019 mean?',
    ['Clients can buy more units', 'The manager can create more units', 'The manager does not need to value the units', 'There is flexibility in the taxation of units'],1,
    'Open-ended means the manager can create additional units in response to investor demand (and must buy them back on request).'),
  q('c1-u1-t4b-q12','cemap1','unit1','t4b','Which statement is correct regarding a unit trust?',
    ['A gain on sale of units may be liable to capital gains tax', 'The fund manager is able to borrow', 'An investor wanting capital growth should buy distribution units', 'The purchase price is called the bid price'],0,
    'Investors in unit trusts are potentially liable to CGT if they realise a gain when selling their units.'),
  q('c1-u1-t4b-q13','cemap1','unit1','t4b','Historically, charges on unit trusts have generally comprised:',
    ['A bid-offer spread only', 'An annual management charge only', 'An annual management charge and a policy fee', 'A bid-offer spread and an annual or monthly management charge'],3,
    'Traditional unit trust charges combine the bid-offer spread (or initial charge) with an ongoing annual management charge.'),
  q('c1-u1-t4b-q14','cemap1','unit1','t4b','Under a unit trust, what does the cancellation price represent?',
    ['The maximum price for a full encashment', 'The minimum price at which investors may cash in units', 'The price applicable during the cooling-off period', 'A rarely-used lower price the manager may use to buy back units if unable to resell them promptly'],3,
    'The cancellation price is a rarely-used, lower-than-bid price used when the manager has little prospect of reselling repurchased units quickly, typically in falling markets.'),
  q('c1-u1-t4b-q15','cemap1','unit1','t4b','Which BEST describes an investment trust?',
    ['A unit-linked single premium whole-of-life policy investing solely in shares', 'A trust investing solely in AIM shares', 'A company which invests in shares of other companies', 'A partnership which invests in gilt-edged securities'],2,
    'Despite the name, an investment trust is a listed company whose business is investing in shares of other companies.'),
  q('c1-u1-t4b-q16','cemap1','unit1','t4b','Why does a collective investment scheme carry reduced risk compared with direct equity investment?',
    ['It invests in a large number of different companies', 'Fund managers can negotiate higher dividend payments', 'It invests in equities not available to individuals', 'Collectives must guarantee return of capital'],0,
    'Pooling investors\u2019 money allows the manager to spread investment across many companies, diversifying away much company-specific risk.'),
  q('c1-u1-t4b-q17','cemap1','unit1','t4b','Which is true of the manager of an investment trust?',
    ['They cannot borrow funds', 'They can borrow to improve income and capital growth', 'They can issue or repurchase units according to demand', 'They can cancel units if the fund grows sharply'],1,
    'Investment trust managers can use gearing (borrowing) to try to enhance returns — a feature unique to investment trusts among the three collective structures.'),

  // ================= CeMAP 1, Unit 1, Topic 4 Part 3 — Retirement & Borrowing (16 Qs) =================
  q('c1-u1-t4c-q1','cemap1','unit1','t4c','Personal pension contributions qualify for tax relief until the individual reaches what age?',
    ['55', '57', '67', '75'],3,
    'Tax relief on personal pension contributions is available to UK residents under age 75.'),
  q('c1-u1-t4c-q2','cemap1','unit1','t4c','Which person could NOT benefit from tax relief on personal pension contributions?',
    ['Jack, 25, earning £50,000', 'Shaila, a full-time carer with no income', 'Bryan, 77, earning £5,000', 'Ben, aged 8, receiving £8,000 from a trust'],2,
    'At 77, Bryan is over the age-75 cut-off for pension tax relief, regardless of his earnings.'),
  q('c1-u1-t4c-q3','cemap1','unit1','t4c','The Enterprise Investment Scheme is designed to attract investment in all of the following EXCEPT:',
    ['A company featuring in the FTSE 250 index', 'A scheme offering tax relief', 'Higher-risk companies', 'Smaller companies'],0,
    'EIS targets smaller, higher-risk unlisted (or AIM-listed) companies — a FTSE 250 constituent is far too large and established to qualify.'),
  q('c1-u1-t4c-q4','cemap1','unit1','t4c','Roisin qualifies for 30% tax relief on an investment. Which product must this be?',
    ['Personal pension plan', 'ISA', 'Venture Capital Trust', 'Offshore account'],2,
    'VCTs (and EIS) offer 30% income tax relief on qualifying investment amounts — ISAs and pensions don\u2019t work this way.'),
  q('c1-u1-t4c-q5','cemap1','unit1','t4c','For which situation might a joint whole-of-life policy be most suitable?',
    ['Ken and Sheila, a retired couple wanting to provide a tax-free legacy', 'Simon and Lois, wanting to maximise savings', 'Vince and Lucy, wanting a lump sum for old age', 'Bernard and Rita, newly married, seeking a mortgage'],0,
    'Whole-of-life cover (often joint-life second-death) is well suited to guaranteeing a tax-free legacy or covering an IHT bill, unlike fixed-term needs such as a new mortgage.'),
  q('c1-u1-t4c-q6','cemap1','unit1','t4c','Which is a feature of a repayment mortgage?',
    ['Repayments are fixed throughout the term', 'The capital and interest payment proportions change over the term', 'The capital balance does not reduce over the term', 'The borrower must take out an investment policy to cover a shortfall'],1,
    'The split between capital and interest within each payment shifts progressively as the outstanding balance reduces.'),
  q('c1-u1-t4c-q7','cemap1','unit1','t4c','Which is true in relation to re-mortgages and second mortgages?',
    ['A second mortgage is an additional loan from a new lender', 'A re-mortgage is an additional loan from a new lender', 'A re-mortgage lets a lender charge a higher rate', 'A second mortgage increases the loan from the same lender'],0,
    'A second mortgage is a further, separate loan secured against the same property, typically from a different lender than the first mortgage.'),
  q('c1-u1-t4c-q8','cemap1','unit1','t4c','Which is true of capital repayments on a repayment mortgage?',
    ['It reduces by an even amount each year', 'Most capital is repaid towards the beginning of the term', 'Most capital is repaid towards the end of the term', 'It remains the same'],2,
    'The capital repayment element accelerates over the term, so most capital is repaid in the later years.'),
  q('c1-u1-t4c-q9','cemap1','unit1','t4c','The main advantage of writing a life assurance policy in trust is to:',
    ['Create a tax-exempt fund', 'Ensure the policy obtains qualifying status', 'Ring-fence the proceeds outside the individual\u2019s estate', 'Increase personal allowances'],2,
    'Writing a policy in trust keeps its proceeds outside the policyholder\u2019s estate for IHT purposes and speeds up payment to beneficiaries.'),
  q('c1-u1-t4c-q10','cemap1','unit1','t4c','Which individual would automatically be subject to auto-enrolment rules?',
    ['Jenny, a 32-year-old teacher earning £38,000', 'Jack, 21, a footballer earning £1m', 'Ben, 25, a part-time cleaner earning £8,000', 'Barbara, 32, a sole trader hairdresser earning £50,000'],0,
    'Jenny meets both the age (22+) and earnings (over £10,000) thresholds for auto-enrolment as an employee; the others fail the age, earnings, or employment-status tests.'),
  q('c1-u1-t4c-q11','cemap1','unit1','t4c','What determines the priority of legal mortgages in England and Wales?',
    ['Date of registration', 'Order in which claims for repayment are made', 'Amount of equity', 'Size of mortgage'],0,
    'Mortgage priority is fixed by the order in which each charge was registered at the Land Registry.'),
  q('c1-u1-t4c-q12','cemap1','unit1','t4c','A repossessed property sale realises a £25,000 surplus, with three further mortgagees. What happens to the surplus?',
    ['It passes directly to the former borrower to settle other debts themselves', 'The society settles only the second mortgagee\u2019s debt and returns the rest to the borrower', 'The society\u2019s only obligation is to the second mortgagee', 'Each subsequent mortgagee is asked to confirm amounts owed, and the surplus is distributed accordingly'],3,
    'The surplus is passed down the chain of registered charges in priority order, with each subsequent lender repaid before any final surplus reaches the borrower.'),
  q('c1-u1-t4c-q13','cemap1','unit1','t4c','Which is true regarding occupational pension schemes?',
    ['A DC scheme provides a minimum guaranteed pension income', 'DB is the most common scheme in the private sector', 'DC is the most common scheme in the public sector', 'On a DB scheme, the employer guarantees a pension based on a fraction of final/career-average salary'],3,
    'Defined Benefit schemes guarantee a pension calculated as a fraction of salary — DC schemes (now dominant in the private sector) offer no such guarantee.'),
  q('c1-u1-t4c-q14','cemap1','unit1','t4c','Which mortgage type is generally most appropriate for a risk-averse customer?',
    ['Interest-only supported by a personal pension plan', 'Interest-only supported by a unit trust', 'Interest-only supported by a stocks & shares ISA', 'A repayment mortgage'],3,
    'A repayment mortgage guarantees the debt clears by the end of the term provided payments are maintained, unlike any interest-only option relying on investment performance.'),
  q('c1-u1-t4c-q15','cemap1','unit1','t4c','Which statement is true regarding contributions to a personal pension for tax relief eligibility?',
    ['£3,600 is the maximum annual contribution allowed', 'There is no limit on contributions', 'Total contributions are limited to the greater of £3,600 or earned income, subject to the annual allowance', 'Contributions are capped at 25% of income'],2,
    'The tax-relief-eligible contribution limit is the greater of £3,600 or earned income, subject to the overall annual allowance.'),
  q('c1-u1-t4c-q16','cemap1','unit1','t4c','Which is true regarding auto-enrolment occupational pension contributions?',
    ['4% employee, 3% employer, 1% government tax relief', '3% employee, 4% employer, 1% government tax relief', '4% employee, 4% employer, no government contribution', '4% employee, 2% employer, 2% government tax relief'],0,
    'The standard minimum 8% total splits as 4% employee, 3% employer and 1% government tax relief.'),

  // ================= CeMAP 1, Unit 1, Topic 5 — Legal Principles (20 Qs) =================
  q('c1-u1-t5-q1','cemap1','unit1','t5','If a person dies without a valid will, what document do their legal representatives require to deal with the estate?',
    ['Grant of Probate', 'Grant of Letters of Administration', 'Codicil', 'Deed of Variation'],1,
    'Where there is no valid will, the personal representatives (administrators) must obtain a Grant of Letters of Administration rather than a Grant of Probate.'),
  q('c1-u1-t5-q2','cemap1','unit1','t5','Bruce appointed his sister Angela to collect rent and keep his buy-to-let properties in good order while abroad. Angela decided to evict troublesome tenants and re-let a property. This is an example of:',
    ['Acting as principal', 'Acting with apparent authority', 'Ratification', 'Utmost good faith'],1,
    'Angela\u2019s actions go beyond her literal instructions, but a reasonable person could conclude Bruce\u2019s general grant of authority over the properties covered this — apparent authority.'),
  q('c1-u1-t5-q3','cemap1','unit1','t5','An LLP will pay which type of tax on its profits?',
    ['Corporation Tax', 'VAT', 'Income Tax', 'Capital Gains Tax'],2,
    'LLP partners are taxed as self-employed individuals on an income tax basis, not via corporation tax.'),
  q('c1-u1-t5-q4','cemap1','unit1','t5','Martin set up a trust for his three grandchildren with two trustees having discretion. Which is true?',
    ['Martin is the testator and the grandchildren the beneficiaries', 'The Trustee Act 2000 requires the grandchildren to obtain advice on investments', 'The trustees have no legal interest in the trust property', 'Both trustees must agree before exercising their discretionary powers'],3,
    'Where trustees hold discretionary powers, all trustees must agree before exercising them.'),
  q('c1-u1-t5-q5','cemap1','unit1','t5','An agent\u2019s recent act has been subject to \u2018ratification\u2019. This implies the agent has:',
    ['Exceeded their authority', 'Asked their principal to deal directly with a client', 'Received money or money\u2019s worth from a client', 'Submitted a written contract'],0,
    'Ratification occurs when a principal accepts an agent\u2019s action that went beyond their actual authority.'),
  q('c1-u1-t5-q6','cemap1','unit1','t5','Under the Consumer Insurance (Disclosure and Representations) Act 2012, \u2018utmost good faith\u2019 now means:',
    ['The proposer must answer honestly and truthfully all application questions', 'The insurer must manage client money ethically and legally', 'All life assurance contracts are based on anticipated financial loss', 'Firms base underwriting on the information provided, not prejudice'],0,
    'The 2012 Act replaced a broad duty to volunteer everything with a duty on the customer to take reasonable care in answering the insurer\u2019s specific questions honestly.'),
  q('c1-u1-t5-q7','cemap1','unit1','t5','Walter and Winnie own their house as joint tenants. If Walter dies:',
    ['His share passes automatically to Winnie', 'Winnie must purchase Walter\u2019s share', 'His share passes to whoever is named in his will', 'Winnie owns 50% but Walter retains an interest in the rest'],0,
    'Under a joint tenancy, the deceased\u2019s interest passes automatically to the surviving joint owner(s) by survivorship, regardless of any will.'),
  q('c1-u1-t5-q8','cemap1','unit1','t5','The difference between a Lasting Power of Attorney and an ordinary Power of Attorney is that:',
    ['An LPA can be revoked at any time by the donor, whereas an ordinary PoA can only be revoked by the Court of Protection', 'An ordinary PoA becomes invalid if the donor loses mental capacity, whereas an LPA remains effective', 'An LPA can be agreed verbally, but an ordinary PoA must be registered', 'An ordinary PoA remains valid if the donor loses mental capacity, whereas an LPA becomes invalid'],1,
    'An ordinary Power of Attorney automatically ends on loss of mental capacity; a Lasting Power of Attorney is specifically designed to remain (or take) effect once that happens.'),
  q('c1-u1-t5-q9','cemap1','unit1','t5','Tom was declared bankrupt in June 2024. For how long will his bankruptcy order remain in place?',
    ['Until June 2027', 'Until June 2026', 'Until June 2025', 'Until June 2030'],2,
    'Bankruptcy lasts 1 year following the Enterprise Act 2002, so Tom\u2019s order would end in June 2025.'),
  q('c1-u1-t5-q10','cemap1','unit1','t5','Peter, Paul and Pamela own a house as tenants in common, each with a 1/3 share. On Paul\u2019s death:',
    ['Peter and Pamela automatically increase their share to 50% each', 'His estate is obliged to sell his share to Peter and Pamela', 'The ultimate beneficiary of Paul\u2019s share is determined by his will or intestacy rules', 'Peter and Pamela must purchase Paul\u2019s share from his estate'],2,
    'As a tenant in common, Paul\u2019s defined 1/3 beneficial share passes according to his will (or intestacy), unlike a joint tenancy where it would pass automatically to the survivors.'),
  q('c1-u1-t5-q11','cemap1','unit1','t5','What role do the Court of Protection and the Office of the Public Guardian play with Lasting Powers of Attorney?',
    ['An LPA can be revoked by the donor at any time whether or not they have capacity', 'LPAs must be registered with the Office of the Public Guardian', 'Any action by attorneys must be agreed by the Court of Protection', 'The Court of Protection keeps a list of all qualified attorneys'],1,
    'Lasting Powers of Attorney must be registered with the Office of the Public Guardian before they can be used.'),
  q('c1-u1-t5-q12','cemap1','unit1','t5','What requirement rests on a discharged bankrupt applying for a mortgage?',
    ['As he is now discharged, there is no requirement', 'To disclose the previous bankruptcy to the lender', 'To disclose the previous bankruptcy to a credit reference agency', 'To ensure the lender conducts a thorough credit search'],1,
    'A discharged bankrupt must always disclose their previous bankruptcy on any future credit or mortgage application.'),
  q('c1-u1-t5-q13','cemap1','unit1','t5','Any debt incurred by a partnership is usually:',
    ['The responsibility of the partners', 'Written off', 'Deducted from future dividends', 'The responsibility of the shareholders'],0,
    'Since a partnership isn\u2019t a separate legal entity, the partners themselves are jointly and severally liable for its debts.'),
  q('c1-u1-t5-q14','cemap1','unit1','t5','Which item of property would be referred to as \u2018personalty\u2019?',
    ['A collection of vintage wines', 'A detached house', 'A paddock used for grazing horses', 'A Victorian factory building'],0,
    'Personalty is any property that is not land — wine, being movable personal property, qualifies; the other three are all forms of realty (land).'),
  q('c1-u1-t5-q15','cemap1','unit1','t5','One financial restriction on undischarged bankrupts is that:',
    ['They can only borrow nominal amounts of money', 'They cannot buy goods except for their own consumption', 'They cannot contribute to protection policies', 'They can only work on an employed basis'],0,
    'Undischarged bankrupts are restricted to borrowing only nominal amounts without disclosing their bankrupt status.'),
  q('c1-u1-t5-q16','cemap1','unit1','t5','Which is true in relation to powers of attorney?',
    ['It is still possible to register an enduring PoA set up before October 2007', 'A Lasting PoA can only give authority over the donor\u2019s finances', 'All powers of attorney give authority to make decisions as soon as they are registered', 'An ordinary power of attorney cannot be revoked'],0,
    'Enduring Powers of Attorney set up on or before October 2007 remain valid and can still be registered, even though new arrangements must now be Lasting Powers of Attorney.'),
  q('c1-u1-t5-q17','cemap1','unit1','t5','Colin is in debt and wants to petition for his own bankruptcy. What minimum debt amount is required?',
    ['He cannot petition for his own bankruptcy', 'There is no minimum amount', '£1,500', '£5,000'],1,
    'An individual can petition for their own bankruptcy regardless of the debt amount — the £5,000 threshold only applies to a creditor petitioning against them.'),
  q('c1-u1-t5-q18','cemap1','unit1','t5','Adrian died flying his private plane; the insurer has established his non-disclosure of the flying hobby was careless (not deliberate), and would have excluded flying from cover had it been disclosed. What is the insurer\u2019s obligation?',
    ['Pay the claim on a proportionate basis', 'Pay the claim in full', 'Refund the premiums paid up to Adrian\u2019s death', 'The insurer has no further obligation'],2,
    'Where careless (not reckless) non-disclosure means the insurer would have declined cover entirely, the claim can be rejected but the premiums must be refunded.'),
  q('c1-u1-t5-q19','cemap1','unit1','t5','Anna is a partner in a business; Jane is a shareholder director of a limited company. Which is true?',
    ['Only Jane has liability for her business\u2019s debts', 'Neither Anna nor Jane has any liability for their businesses\u2019 debts', 'Only Anna has liability for her business\u2019s debts', 'Both Anna and Jane are liable for their businesses\u2019 debts'],2,
    'As a partner, Anna is personally liable for partnership debts; as a shareholder in a limited company, Jane has no personal liability beyond her investment.'),
  q('c1-u1-t5-q20','cemap1','unit1','t5','How many \u2018designated partners\u2019 are required for a Limited Liability Partnership?',
    ['There is no minimum', 'At least two', 'At least three', 'At least four'],1,
    'An LLP must have at least two designated partners responsible for statutory reporting requirements.'),

  // ================= CeMAP 1, Unit 1, Topic 6 — Wills, Intestacy & Trusts (15 Qs) =================
  q('c1-u1-t6-q1','cemap1','unit1','t6','What is the benefit of a \u2018deed of variation\u2019 to a beneficiary under a will?',
    ['Inheritance tax advantages can be obtained', 'A person can reject a gift given to them', 'It is a way of avoiding intestacy', 'It is a way of meeting the deceased\u2019s wishes'],0,
    'A deed of variation is most commonly used to redirect an inheritance for tax-planning (usually IHT) reasons.'),
  q('c1-u1-t6-q2','cemap1','unit1','t6','Joe and Lucy want to leave everything to the surviving spouse then split equally between their children, and want to prevent a future new spouse from inheriting if the survivor remarries. What achieves this?',
    ['A mirror will', 'A discretionary trust', 'Mutual wills', 'The intestacy rules automatically achieve this'],2,
    'Mutual wills bind the survivor not to change the agreed terms after taking a benefit under the first death, preventing a later spouse from being written in instead.'),
  q('c1-u1-t6-q3','cemap1','unit1','t6','A man dies intestate leaving a widow and children with a £522,000 estate; the statutory legacy is £322,000. What is the MAXIMUM cash sum the widow receives?',
    ['£522,000', '£325,000', '£500,000', '£422,000'],3,
    'The widow receives the £322,000 statutory legacy plus half of the remaining £200,000 (£100,000) = £422,000.', undefined, undefined, true),
  q('c1-u1-t6-q4','cemap1','unit1','t6','Despite his recent marriage to Katrina, John\u2019s existing will has remained in force. Why?',
    ['The will was written with the wedding in mind', 'The will was witnessed by Katrina and her father', 'John has no children or other dependants', 'John\u2019s estate is valued at £199,000'],0,
    'Marriage only fails to revoke a will where the will was made in contemplation of that specific marriage.'),
  q('c1-u1-t6-q5','cemap1','unit1','t6','Harry died intestate, divorced with no children. His parents (also divorced, since deceased) had no more children, but his mother Anne remarried and had a daughter Grace, who had a son Andrew. Both Anne and Grace have since died; Anne is survived by husband Ron, Grace by partner Gary and son Andrew. Who inherits Harry\u2019s estate?',
    ['Ron', 'Gary', 'Andrew', 'The Crown'],2,
    'Half-siblings count under intestacy — Grace (Harry\u2019s half-sister) would have inherited but predeceased him, so her son Andrew inherits in her place; Ron and Gary have no blood relationship to Harry.'),
  q('c1-u1-t6-q6','cemap1','unit1','t6','Joanna is a trust beneficiary who will only benefit if another beneficiary dies before the settlor. This makes her a:',
    ['Life tenant', 'Contingent beneficiary', 'Discretionary beneficiary', 'Direct beneficiary'],1,
    'Her entitlement depends on a future uncertain event, making her a contingent beneficiary.'),
  q('c1-u1-t6-q7','cemap1','unit1','t6','John\u2019s will splits his estate equally between three of his four children; his eldest son James was excluded. Two of the three, Chloe and Patrick, want James to benefit and are willing to give up some of their own share; the third, Alison, disagrees and wants her full entitlement. What is the position on a deed of variation?',
    ['Alison cannot object but keeps her full entitlement', 'It is too late to arrange a deed of variation', 'Alison would have to agree to any variation affecting her share', 'The deed can go ahead regardless of what Chloe and Patrick decide about Alison'],0,
    'Only beneficiaries adversely affected by a variation need to agree — Alison, whose share is unaffected by Chloe and Patrick\u2019s own gift, has no right to object and keeps her full share.'),
  q('c1-u1-t6-q8','cemap1','unit1','t6','Which is NOT a requirement for a will to be valid? It must be:',
    ['In writing, typed or printed', 'Signed', 'Dated', 'Witnessed by two people'],2,
    'There is no legal requirement for a will to be dated, although failing to do so can cause problems if multiple wills exist.'),
  q('c1-u1-t6-q9','cemap1','unit1','t6','Jenny witnessed her mother-in-law Betty\u2019s will, which leaves 50% to her daughter, 25% to Jenny\u2019s husband (Betty\u2019s son), and 25% to Jenny. What is the legal position on Betty\u2019s death?',
    ['All beneficiaries receive their full inheritance', 'The will is invalid, so Betty died intestate', 'The will is valid but Jenny and her husband cannot benefit', 'The will is valid but only Jenny\u2019s husband and his sister can benefit'],3,
    'A witness (Jenny) forfeits her own gift; her husband\u2019s gift is unaffected since he did not witness the will — the will remains valid overall.'),
  q('c1-u1-t6-q10','cemap1','unit1','t6','When someone dies intestate, how many days must their spouse survive them to benefit?',
    ['7', '21', '28', '31'],2,
    'A surviving spouse must survive the deceased by 28 days to inherit under the intestacy rules.'),
  q('c1-u1-t6-q11','cemap1','unit1','t6','Pavel\u2019s will includes an immediate post-death interest trust, paying income to his wife Emily until her death, with assets then passing to daughter Paula. Which is true?',
    ['Paula is the remainderman', 'No IHT is payable on the money passing into the trust on Pavel\u2019s death', 'A 20% IHT charge applies when the trust is set up', 'Emily is the contingent beneficiary'],0,
    'Paula, who benefits after Emily\u2019s interest ends, is the remainderman; Emily is the life tenant, and the transfer on death is taxed as a normal legacy (not a lifetime chargeable transfer).'),
  q('c1-u1-t6-q12','cemap1','unit1','t6','Roman plans to gift money to a discretionary trust for his grandchildren. What is the IHT position on the gift?',
    ['There may be a 20% IHT charge when he makes the gift', 'There may be a 40% IHT charge when he makes the gift', 'There will not be any IHT on the gift', 'His estate may have to pay 20% IHT only if he survives seven years'],0,
    'A lifetime gift into a discretionary trust is a chargeable lifetime transfer, potentially triggering an immediate 20% charge on any amount above the nil rate band.'),
  q('c1-u1-t6-q13','cemap1','unit1','t6','Piotr has a combined life and critical illness policy. What type of trust gives him access to the CIC benefit but keeps his death benefit out of his estate?',
    ['A discretionary trust', 'A split trust', 'A bare trust', 'An interest in possession trust'],1,
    'A split trust separates the living-benefit critical illness cover (accessible to Piotr) from the life cover element (held in trust, outside his estate).'),
  q('c1-u1-t6-q14','cemap1','unit1','t6','Jerry has taken out a life policy where benefits are automatically in trust for his wife and three children. What type of trust applies?',
    ['An absolute trust', 'A discretionary trust', 'A Married Women\u2019s Property Act (1882) trust', 'A flexible trust'],2,
    'A life policy taken out for the specific benefit of a spouse/children automatically creates an MWPA trust, keeping proceeds outside the policyholder\u2019s estate.'),
  q('c1-u1-t6-q15','cemap1','unit1','t6','Gary set up a designated account for his son Alexander when he was born. At what age can Alexander take over control of the account?',
    ['12', '16', '18', '21, if the balance exceeds a specified amount'],2,
    'A child gains control of a designated account at 18, at which point it can be transferred fully into their own name.'),

  // ================= CeMAP 1, Unit 1, Topic 7 — Development of UK Regulation (12 Qs) =================
  q('c1-u1-t7-q1','cemap1','unit1','t7','Which legislation led to the creation of the PRA and FCA?',
    ['Financial Services Act 1986', 'Financial Services and Markets Act 2000', 'Financial Services Act 2012', 'Bank of England and Financial Services Act 2016'],2,
    'The Financial Services Act 2012 introduced the twin peaks model of the PRA and FCA, effective from April 2013.'),
  q('c1-u1-t7-q2','cemap1','unit1','t7','When did mortgage activities become regulated by the FSA?',
    ['December 2001', 'October 2004', 'January 2005', 'April 2013'],1,
    'Mortgage regulation began in October 2004, with insurance following in January 2005.'),
  q('c1-u1-t7-q3','cemap1','unit1','t7','What is one of the main powers granted to the Financial Policy Committee?',
    ['Ensure the relevant markets function well', 'Intervene in the authorisation of dual-regulated firms', 'Make recommendations to the PRA and the FCA', 'Set interest rates to manage the money supply'],2,
    'The FPC monitors systemic risk and makes recommendations to the PRA and FCA — it does not itself set interest rates (that\u2019s the MPC) or handle authorisation.'),
  q('c1-u1-t7-q4','cemap1','unit1','t7','Which body is responsible for maintaining UK financial stability through \u2018macroprudential supervision\u2019?',
    ['Prudential Regulation Authority', 'Financial Policy Committee', 'Financial Conduct Authority', 'HM Treasury'],1,
    'The Financial Policy Committee has the specific remit of macroprudential (system-wide) supervision.'),
  q('c1-u1-t7-q5','cemap1','unit1','t7','Which legislation provides for retained EU laws to be repealed and replaced by UK-specific rules?',
    ['Future Regulatory Framework (FRF)', 'European Union (Withdrawal) Act 2018', 'Financial Services Act 2021', 'Financial Services and Markets Act 2023'],3,
    'The Financial Services and Markets Act 2023 established the Future Regulatory Framework Review and enabled repeal/replacement of retained EU rules.'),
  q('c1-u1-t7-q6','cemap1','unit1','t7','Which body\u2019s role is to "promote an environment where people can be confident they are getting great choices and fair deals"?',
    ['Financial Policy Committee', 'Financial Conduct Authority', 'The Competition and Markets Authority', 'Advertising Standards Authority'],2,
    'This is the CMA\u2019s stated mission, focused on competition and consumer protection in markets generally.'),
  q('c1-u1-t7-q7','cemap1','unit1','t7','Jonathan wants to complain about late income payments from his occupational pension scheme. Where should his complaint go first?',
    ['The pension company', 'The scheme trustees', 'The Financial Ombudsman Service', 'The Financial Conduct Authority'],1,
    'Occupational pension scheme complaints must first go to the scheme trustees under the Internal Dispute Resolution Procedure.'),
  q('c1-u1-t7-q8','cemap1','unit1','t7','Which is NOT a responsibility of the Competition and Markets Authority?',
    ['Protecting consumers from unfair trading practices', 'Investigating corporate mergers', 'Ensuring relevant markets function well', 'Taking action to prevent anti-competitive behaviour'],2,
    '"Ensuring relevant markets function well" is the FCA\u2019s strategic objective, not a CMA responsibility.'),
  q('c1-u1-t7-q9','cemap1','unit1','t7','Which of the following is NOT exempt from authorisation under FSMA 2000?',
    ['An independent financial advisory firm', 'Trustees', 'The Bank of England', 'The London Stock Exchange'],0,
    'An IFA firm carrying out regulated activities requires full FCA authorisation — trustees, the Bank of England and recognised exchanges are specifically exempted.'),
  q('c1-u1-t7-q10','cemap1','unit1','t7','The Information Commissioner has responsibilities under which Act(s)?',
    ['Data Protection Act only', 'Financial Services Act 2012 and Data Protection Act 2018', 'Financial Services Act 2012 only', 'Data Protection Act 2018 and Freedom of Information Act 2000'],3,
    'The Information Commissioner enforces both the Data Protection Act 2018 and the Freedom of Information Act 2000.'),
  q('c1-u1-t7-q11','cemap1','unit1','t7','Which oversight group would most likely review and publish a financial institution\u2019s financial statements and accounts?',
    ['Compliance officers', 'Trustees', 'Internal auditors', 'External auditors'],3,
    'External auditors independently review and report on a firm\u2019s published financial statements and accounts.'),
  q('c1-u1-t7-q12','cemap1','unit1','t7','Maria\u2019s occupational pension complaint is being considered by the trustees under the IDRP. How long do they have to provide a formal response?',
    ['28 days', '4 months', '8 weeks', '1 month'],1,
    'The IDRP allows trustees up to 4 months from receipt to provide a formal response to a complaint.'),

  // ================= CeMAP 1, Unit 1, Topic 8 Part 1 — PRA & FCA Approach (15 Qs) =================
  q('c1-u1-t8a-q1','cemap1','unit1','t8a','Which is NOT a PRA objective?',
    ['To promote the safety and soundness of the firms it regulates', 'To ensure that the relevant markets function well', 'To facilitate effective competition between firms', 'To facilitate the international competitiveness of the UK economy'],1,
    '"Ensuring relevant markets function well" is the FCA\u2019s strategic objective, not one of the PRA\u2019s four statutory objectives.'),
  q('c1-u1-t8a-q2','cemap1','unit1','t8a','What term describes an FCA-regulated firm supervised by a specific dedicated team rather than the general supervision team?',
    ['Flexible portfolio', 'Higher-risk portfolio', 'Defined portfolio', 'Fixed portfolio'],3,
    'Fixed portfolio firms — typically large banking/insurance groups — get a named, dedicated supervisory team.'),
  q('c1-u1-t8a-q3','cemap1','unit1','t8a','The FCA supervision model is based on three pillars. Which is NOT one of them?',
    ['Directive', 'Proactive', 'Reactive', 'Thematic'],0,
    'The three pillars are Proactive, Reactive and Thematic — "Directive" is not one of them.'),
  q('c1-u1-t8a-q4','cemap1','unit1','t8a','Which FCA enforcement action would NOT require an application to the court?',
    ['Injunction', 'Restitution', 'Redress', 'Withdrawal of a person\u2019s approval'],3,
    'Withdrawal of approval can be actioned directly by the FCA, unlike injunctions, restitution and redress, which all require a court order.'),
  q('c1-u1-t8a-q5','cemap1','unit1','t8a','The FCA\u2019s single strategic objective is to:',
    ['Govern organisations managing investments for others', 'Ensure that relevant markets are working well', 'Regulate the marketing and sale of all life assurance products', 'Oversee the administration of all types of investment business'],1,
    'The FCA\u2019s one strategic objective is to ensure that relevant markets function well.'),
  q('c1-u1-t8a-q6','cemap1','unit1','t8a','Which is NOT one of the FCA\u2019s operational objectives?',
    ['Reducing the scope for financial crime', 'Protecting and enhancing the integrity of the UK financial system', 'Protecting competition in the interests of consumers', 'Securing an appropriate degree of protection for consumers'],0,
    'The three FCA operational objectives are consumer protection, market integrity, and competition — reducing financial crime is a related activity but not one of the three named operational objectives.'),
  q('c1-u1-t8a-q7','cemap1','unit1','t8a','If the FCA varies a firm\u2019s permissions following a rule breach, this means:',
    ['The firm may have one of its regulated activities removed', 'The firm must sell assets to provide restitution', 'The firm must seek authorisation from a different regulator', 'The firm must submit each sale to the FCA for approval'],0,
    'Varying permissions typically means removing the firm\u2019s ability to carry out a specific regulated activity.'),
  q('c1-u1-t8a-q8','cemap1','unit1','t8a','A specific responsibility of the FCA is to:',
    ['Maintain financial system stability through macro-prudential supervision', 'Take action to prevent anti-competitive behaviour', 'Understand the main threats to financial system stability', 'Oversee the prudential supervision of firms not supervised by the PRA'],3,
    'The FCA carries out prudential supervision of the smaller, solo-regulated firms that the PRA doesn\u2019t prudentially regulate.'),
  q('c1-u1-t8a-q9','cemap1','unit1','t8a','Under its enforcement powers, forcing an individual to forfeit profit made in contravention of the regulations is known as:',
    ['Damages', 'Redress', 'Restitution', 'Restoration'],2,
    'Restitution is the term for a court order requiring forfeiture of ill-gotten profits.'),
  q('c1-u1-t8a-q10','cemap1','unit1','t8a','How many primary strategic objectives does the FCA have?',
    ['One', 'None', 'Two', 'Three'],0,
    'The FCA has exactly one strategic objective, supported by three operational objectives.'),
  q('c1-u1-t8a-q11','cemap1','unit1','t8a','Which body is responsible for the prudential regulation of credit unions?',
    ['The Prudential Regulation Authority', 'The Bank of England', 'The Financial Ombudsman Service', 'The Financial Conduct Authority'],0,
    'Credit unions are prudentially regulated by the PRA.'),
  q('c1-u1-t8a-q12','cemap1','unit1','t8a','Which part of the FCA Handbook covers the Principles for Businesses?',
    ['Business Standards', 'High Level Standards', 'Prudential Standards', 'Training and Competence'],1,
    'The Principles for Businesses sit within the Handbook\u2019s High Level Standards section.'),
  q('c1-u1-t8a-q13','cemap1','unit1','t8a','Conduct regulation focuses on the way a financial firm:',
    ['Holds sufficient funds to cover potential losses', 'Manages its financial risks', 'Meets its financial obligations', 'Markets its products and deals with its customers'],3,
    'Conduct regulation (the FCA\u2019s remit) is about how firms sell to and treat their customers, as distinct from prudential (financial soundness) regulation.'),
  q('c1-u1-t8a-q14','cemap1','unit1','t8a','Which organisation makes use of a Proactive Intervention Framework (PIF)?',
    ['The Bank of England', 'The FCA', 'The FOS', 'The PRA'],3,
    'The PRA uses the Proactive Intervention Framework to help identify early risks to a firm\u2019s viability.'),
  q('c1-u1-t8a-q15','cemap1','unit1','t8a','Which body has the objective of securing an appropriate degree of protection for insurance policyholders?',
    ['The Bank of England', 'The FCA', 'The Pensions Regulator', 'The PRA'],3,
    'Protecting insurance policyholders appropriately is one of the PRA\u2019s four statutory objectives.'),

  // ================= CeMAP 1, Unit 1, Topic 8 Part 2 — PRA & FCA Approach (18 Qs) =================
  q('c1-u1-t8b-q1','cemap1','unit1','t8b','An IFA has identified £50 in a client\u2019s dormant account. Considering \u2018paying away\u2019 the money to charity, which is correct?',
    ['There must have been no activity for at least 12 years', 'The amount is too much to exercise the action', 'The IFA must take reasonable steps to contact the client first', 'The amount must be at least £100'],2,
    'Since £50 exceeds the £25 retail de minimis threshold, the firm must first make reasonable attempts to contact the client before paying the money away.'),
  q('c1-u1-t8b-q2','cemap1','unit1','t8b','Under the SM&CR, a firm required to follow baseline requirements with no additional requirements would be categorised as:',
    ['Enhanced', 'Core', 'Basic', 'Limited scope'],1,
    '"Core" firms must meet the baseline SM&CR requirements — most firms fall into this middle category.'),
  q('c1-u1-t8b-q3','cemap1','unit1','t8b','Under the Certification regime, which body is responsible for assessing and certifying an employee\u2019s fitness and propriety?',
    ['The PRA', 'The firm', 'The FCA', 'An independent body'],1,
    'Unlike the Senior Managers Regime, the Certification Regime is firm-led — the employer itself certifies fitness and propriety, reassessed annually.'),
  q('c1-u1-t8b-q4','cemap1','unit1','t8b','Great Advice Ltd is an appointed representative of Eagle Mortgages. Which is true?',
    ['Great Advice Ltd must be authorised by the FCA', 'The FCA will assess Great Advice Ltd\u2019s directors\u2019 fitness and propriety', 'Eagle Mortgages are responsible for any advice given by Great Advice Ltd', 'Great Advice Ltd must provide complaints/revenue data to the FCA annually'],2,
    'As principal, Eagle Mortgages is ultimately responsible and accountable for its appointed representative\u2019s activities.'),
  q('c1-u1-t8b-q5','cemap1','unit1','t8b','Which BEST describes the relationship between the \u2018fit and proper\u2019 test and the SM&CR?',
    ['A fit and proper test is merely recommended for senior management roles', 'A satisfactory fit and proper test is necessary before an individual can be accepted for a senior management role', 'The test is mainly designed to establish creditworthiness only', 'The test relates solely to previous activity in a controlled function'],1,
    'A satisfactory fit and proper assessment is a precondition for approval to a senior management function.'),
  q('c1-u1-t8b-q6','cemap1','unit1','t8b','Which job applicant is LEAST likely to meet the FCA \u2018fit and proper\u2019 requirements?',
    ['Gill, recently made redundant from an IFA firm', 'Veronica, who missed two mortgage payments following a divorce', 'Josie, whose father\u2019s house was repossessed three years ago', 'Irene, with an authorised £2,000 overdraft'],1,
    'Veronica\u2019s own recent missed mortgage payments are most directly relevant to the financial soundness element of the fit and proper test — the others relate to third parties or are unremarkable financial arrangements.'),
  q('c1-u1-t8b-q7','cemap1','unit1','t8b','Which employees at authorised firms do the Code of Conduct rules apply to?',
    ['All staff', 'Senior managers and certified staff only', 'All staff excluding ancillary staff', 'Senior managers only'],2,
    'The Code of Conduct applies to virtually all staff, with only purely ancillary roles (security, IT, reception, transport) exempt.'),
  q('c1-u1-t8b-q8','cemap1','unit1','t8b','Individuals categorised as performing a \u2018significant harm\u2019 function must be approved by:',
    ['Both the FCA and PRA', 'Either the FCA or PRA', 'Their employing firm under the Certification Regime', 'Their employing firm under the Senior Managers Regime'],2,
    '"Significant harm" roles sit under the Certification Regime, where the firm itself (not the regulator) certifies fitness and propriety.'),
  q('c1-u1-t8b-q9','cemap1','unit1','t8b','Individuals performing which role will be individually vetted and approved by the FCA/PRA?',
    ['Those performing an ancillary role', 'Those performing senior management functions', 'Those in significant harm functions', 'Those in significant harm and senior management functions'],1,
    'Only senior management functions require direct, personal vetting and approval by the regulator; significant harm functions are certified by the firm itself.'),
  q('c1-u1-t8b-q10','cemap1','unit1','t8b','Into which type of function would the Money Laundering Reporting function be categorised?',
    ['Customer function', 'Governing function', 'Risk function', 'Senior management function'],3,
    'The Money Laundering Reporting function is one of the specific senior management functions (SMFs) defined by the FCA/PRA.'),
  q('c1-u1-t8b-q11','cemap1','unit1','t8b','Which bank employee would NOT normally require individual FCA/PRA approval?',
    ['A financial adviser', 'Director of regulated sales', 'Chairperson', 'Money laundering reporting officer'],0,
    'A financial adviser typically falls under the Certification Regime (firm-certified), while the other three roles are senior management functions requiring direct regulator approval.'),
  q('c1-u1-t8b-q12','cemap1','unit1','t8b','Which role at an authorised firm is LEAST likely to be subject to the FCA\u2019s conduct rules for individuals?',
    ['Non-executive director', 'Security officer', 'Marketing director', 'Financial adviser'],1,
    'A security officer\u2019s purely ancillary role means they are least likely to fall under the individual conduct rules, unlike the other customer-facing or governance roles listed.'),
  q('c1-u1-t8b-q13','cemap1','unit1','t8b','Which is NOT one of the components of the FCA\u2019s fit and proper test for Certification Regime individuals?',
    ['Competence and capability', 'Honesty, integrity and reputation', 'Financial soundness', 'Experience and compliance'],3,
    'The three components are honesty/integrity/reputation, competence/capability and financial soundness — "experience and compliance" as a combined category is not one of them.'),
  q('c1-u1-t8b-q14','cemap1','unit1','t8b','Harry\u2019s role falls under the Certification Regime. This means:',
    ['He could have oversight of the firm\u2019s compliance function', 'He must be approved by the FCA', 'His role would be described as a material risk taker', 'His fitness for the role would be assessed bi-annually'],2,
    'Certification Regime roles are those capable of significant harm — "material risk taker" is a typical example of such a role.'),
  q('c1-u1-t8b-q15','cemap1','unit1','t8b','Carlo\u2019s \u2018fit and proper\u2019 assessment involves checking his credit records. This is primarily to assess his:',
    ['Capability', 'Competence', 'Financial soundness', 'Honesty, integrity and reputation'],2,
    'Credit record checks are used primarily to assess an individual\u2019s financial soundness.'),
  q('c1-u1-t8b-q16','cemap1','unit1','t8b','Melanie is subject to the FCA\u2019s Certification Regime at a large authorised firm. What is she MOST likely to be doing?',
    ['Chief executive', 'Human resources officer', 'Non-executive director', 'Mortgage adviser'],3,
    'A customer-facing role such as mortgage adviser is a classic Certification Regime role, while the other three options are senior management functions requiring direct FCA/PRA approval.'),
  q('c1-u1-t8b-q17','cemap1','unit1','t8b','Gary, a senior manager under investigation for a regulatory breach, faces which of these FALSE statements?',
    ['Gary must prove that he took reasonable steps to prevent the breach', 'The regulator must prove Gary was a senior manager at the time of the breach', 'The regulator must prove Gary was responsible for the department that caused the breach', 'The regulator must prove the bank breached the regulations'],0,
    'It is the REGULATOR that must prove all elements of the case (including that reasonable steps were not taken) — the burden is not on Gary to prove his own innocence.'),
  q('c1-u1-t8b-q18','cemap1','unit1','t8b','David performs a significant harm function within his authorised firm. With what minimum frequency must his fitness and propriety be reassessed by the firm?',
    ['Monthly', 'Every three months', 'Every six months', 'Annually'],3,
    'Certification Regime fitness and propriety assessments must be repeated at least annually.')
]

function q(
  id: string, module: 'cemap1'|'cemap2'|'cemap3', unitKey: string, topicKey: string,
  text: string, options: string[], correctIndex: number, explanation: string,
  dateSensitive?: boolean, reviewRequired?: boolean, calculation?: boolean
): Question {
  return {
    id, module, unitKey, topicKey, text, options, correctIndex: [correctIndex], explanation,
    difficulty: 'intermediate', source: `${module.toUpperCase()} topic test`, origin: 'original',
    dateSensitive, reviewRequired, calculation
  }
}
